### ISSUE TITLE
v1 Checklist

### ISSUE THREAD

**Issue by blt950** [blt950/where2fly#16]
- [x] Documentation comments over functions
- [x] Private/Public functions tidy up
- [x] Check for further search optimizations
- [x] Vite cleanup and optimization
- [x] Recurring javascripts are templated
- [x] HTML and accessibility verification
- [x] Consistent tab size 
- [x] Responsive/mobile
- [x] Browser check
- [x] Update npm/composer
